"""
LeetCode Problem - EASY
389. Find the Difference

You are given two strings 's' and 't'.
String 't' is generated by random shuffling string 's' and then add one more letter at a random position.
Return the letter tha was added to 't'.

Example #1
Input: s = "abcd", t = "abcde"
Output: "e"

Example #2
Input: s = "", t = "y"
Output: "y"
"""

def find_the_difference(s, t):
    # in case there 's' is empty string
    if len(s) == 0:
        return t

    sorted_s = sorted(s)
    sorted_t = sorted(t)

    for a,b in zip(sorted_s, sorted_t):
        if a != b:
            return b
    
    return sorted_t[-1]